-- Inserir dados reais de teste no sistema
INSERT INTO "HISTORICO_CHAMADOS" (
    "ID_DO_CASO",
    "TIPO", 
    "RESUMO",
    "DESCRICAO",
    "DATA_ABERTURA",
    "PRIORIDADE",
    "CATEGORIA",
    "STATUS",
    "ATRIBUIDO",
    "GRUPO_ATRIBUIDO",
    "LOCALIZACAO_AFETADA",
    "DATA_RESOLUCAO",
    "VIOLACAO_PROJETADA",
    "RELATADO_POR",
    "METODO_RELATADO",
    "CATEGORIA_REPORTE",
    "ULTIMA_MODIFICACAO",
    "USUARIO_FINAL_AFETADO",
    "EMAIL_USUARIO_FINAL",
    "CPF_USUARIO_FINAL",
    "DESCRICAO_SOLUCAO"
) VALUES (
    2189,
    'Solicitação',
    'Reset de Senha',
    'Solicitação de reset de senha para e-mail nominal: marcos.gouveia',
    '2019-04-29 07:04:19.000',
    'NORMAL',
    'INFRAESTRUTURA.SERVIDOR.ACTIVE DIRECTORY.RESET DE SENHA.ELEGIVEL',
    'ENCERRADO',
    '',
    'SDX SERVICE DESK N1 TELEFONE',
    '51645-VALE PORTO – MANUT PREDIAL E HVAC',
    '2019-04-29 07:06:42.000',
    '2019-04-29 10:04:19.000',
    'Marcos Santos Goveia',
    'Outros',
    'INFRAESTRUTURA.SERVIDOR.ACTIVE DIRECTORY.RESET DE SENHA.ELEGIVEL',
    '2019-05-07 07:36:42.000',
    'Marcos Santos Goveia',
    'marcos.xxx@soxxxo.com',
    '516xxxx',
    'Efetuado reset de senha de e-mail nominal para: marcos.gouveia'
);